'use strict';

/**
 * Wave 0 RED fixture for HRD-01 / B-D04 — SMOKE-TEST.md schema.
 *
 * Asserts that .planning/SMOKE-TEST.md (generated by Plan 01) has the
 * 4 runtime rows × 5 command columns header schema.
 *
 * RED-state contract: Plan 01 generates the file via
 * `brief-tools smoke-test run`. Until then, the file is absent and tests
 * skip with a Plan-01 rationale.
 *
 * Pattern source: tests/architecture-counts.test.cjs (filesystem read)
 * + 09-PATTERNS.md lines 740-765 (SMOKE-TEST.md schema).
 */

const { describe, test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SMOKE_TEST_MD = path.join(ROOT, '.planning', 'SMOKE-TEST.md');

// COMMANDS — byte-identical to 09-00-PLAN.md <interfaces> block (B-D02).
const COMMANDS = ['init', 'define', 'discover', 'design', 'deliver'];

// RUNTIMES (just names) — byte-identical to 09-00-PLAN.md <interfaces> block.
const RUNTIME_NAMES = ['claude', 'codex', 'gemini', 'opencode'];

describe('SMOKE-TEST.md schema (HRD-01 / B-D04)', () => {
  test('SMOKE-TEST.md exists', (t) => {
    if (!fs.existsSync(SMOKE_TEST_MD)) {
      t.skip('blocked: .planning/SMOKE-TEST.md not yet generated (Plan 01)');
      return;
    }
    assert.ok(true, 'SMOKE-TEST.md present');
  });

  test('header row contains 5 command columns: init | define | discover | design | deliver', (t) => {
    if (!fs.existsSync(SMOKE_TEST_MD)) {
      t.skip('blocked: .planning/SMOKE-TEST.md not yet generated (Plan 01)');
      return;
    }
    const content = fs.readFileSync(SMOKE_TEST_MD, 'utf-8');
    const headerRe = /\|\s*Runtime\s*\|\s*init\s*\|\s*define\s*\|\s*discover\s*\|\s*design\s*\|\s*deliver\s*\|/i;
    assert.ok(
      headerRe.test(content),
      `expected header row | Runtime | ${COMMANDS.join(' | ')} | (case-insensitive); got:\n${content.slice(0, 500)}`,
    );
  });

  test('4 runtime rows present (claude, codex, gemini, opencode)', (t) => {
    if (!fs.existsSync(SMOKE_TEST_MD)) {
      t.skip('blocked: .planning/SMOKE-TEST.md not yet generated (Plan 01)');
      return;
    }
    const content = fs.readFileSync(SMOKE_TEST_MD, 'utf-8');
    for (const name of RUNTIME_NAMES) {
      const re = new RegExp(`^\\|\\s*${name}\\s*\\|`, 'mi');
      assert.match(content, re, `missing runtime row for ${name} in SMOKE-TEST.md`);
    }
  });
});
