'use strict';

/**
 * Wave 0 RED fixture for HRD-02 / A-D04 — SURFACE-AUDIT.md schema check.
 *
 * Asserts that .planning/SURFACE-AUDIT.md (generated by Plan 05) has the
 * commands table with 12 rows AND a "Removed in v1" section enumerating
 * the 56 deleted commands.
 *
 * RED-state contract: Plan 05 generates SURFACE-AUDIT.md as part of the
 * pruning step. Until then, the file is absent and tests skip with a
 * Plan-05 rationale.
 *
 * Pattern source: tests/architecture-counts.test.cjs (filesystem read +
 * regex assertion) + 09-PATTERNS.md lines 700-736 (SURFACE-AUDIT.md schema).
 */

const { describe, test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SURFACE_AUDIT_MD = path.join(ROOT, '.planning', 'SURFACE-AUDIT.md');

describe('SURFACE-AUDIT.md schema (HRD-02 / A-D04)', () => {
  test('SURFACE-AUDIT.md exists', (t) => {
    if (!fs.existsSync(SURFACE_AUDIT_MD)) {
      t.skip('blocked: .planning/SURFACE-AUDIT.md not yet generated (Plan 05)');
      return;
    }
    assert.ok(true, 'SURFACE-AUDIT.md present');
  });

  test('commands table has 12 rows (one per LOCKED_12 slug)', (t) => {
    if (!fs.existsSync(SURFACE_AUDIT_MD)) {
      t.skip('blocked: .planning/SURFACE-AUDIT.md not yet generated (Plan 05)');
      return;
    }
    const content = fs.readFileSync(SURFACE_AUDIT_MD, 'utf-8');
    // Match table rows of the form `| <num> | `/brief-<slug>` | ...`
    const rowRe = /^\|\s+\d+\s+\|\s+`\/brief-/gm;
    const matches = content.match(rowRe) || [];
    assert.ok(
      matches.length >= 12,
      `expected ≥12 numbered command rows in SURFACE-AUDIT.md, got ${matches.length}`,
    );
  });

  test('Removed in v1 section exists with 56 or 57 entries', (t) => {
    if (!fs.existsSync(SURFACE_AUDIT_MD)) {
      t.skip('blocked: .planning/SURFACE-AUDIT.md not yet generated (Plan 05)');
      return;
    }
    const content = fs.readFileSync(SURFACE_AUDIT_MD, 'utf-8');
    // 09-00-PLAN.md prose template says "56 commands deleted" but the
    // filesystem-true count is 57 (see Rule 1 deviation in
    // brief-surface-audit-install-cleanup.test.cjs header). Plan 05 may
    // emit either number; accept both so this fixture turns GREEN regardless.
    assert.match(
      content,
      /##\s+Removed in v1.*(56|57)\s+commands/i,
      'expected "## Removed in v1 (56|57 commands deleted)" header (case-insensitive, allow either historical 56 or filesystem-true 57)',
    );
  });
});
